### ISSUE TITLE
demo please

### ISSUE THREAD

**Issue by fyyyyy** [danschumann/limby-resize#2]
Hello, could you provide a demo jsfiddle or jsbin ?
Especially for the canvas resize
Thanks

**Comment by danschumann** [comment]
Sounds like a good idea I'll put one up tonight, with a big image, and then how it looks scaled down w/ my algorithm or another.  Maybe even let them upload their own to test different images.

Sorry I didn't see this sooner, I'm not used to people actually visiting me repos! xD

**Comment by danschumann** [comment]
http://jsbin.com/jocapawere/2/

upload an image to view the 2 outputs.

if you change the scale/factor, you have to upload a different image or refresh first.  Anyway, the bigger the downscaling, the more you can notice how pixelated canvas does it, and mine keeps all color data and shrinks it.

**Comment by danschumann** [comment]
by the way, I uploaded a new version of canvas_resize.js earlier too, it wasn't quite setup for frontend before.

**Comment by danschumann** [comment]
Also, using large images that have text in them ( text is basically unreadable in the native canvas implementation, but mine does a nice job ( what you would expect from photoshop, etc )
![image](https://cloud.githubusercontent.com/assets/1516973/6984700/33ce1276-d9f1-11e4-94d5-ad8a9f7fa5c2.png)

**Comment by danschumann** [comment]
uploading this image to use in readme.md
![image](https://cloud.githubusercontent.com/assets/1516973/6985039/73b5fb4e-d9f4-11e4-921b-6fc873fa0b45.png)

**Comment by fyyyyy** [comment]
this looks great ! thanks :)
