### ISSUE TITLE
Resized image file size

### ISSUE THREAD

**Issue by nghiapd92** [danschumann/limby-resize#3]
Hi, I've just tested your module but I got something abnormal about image size.

Please take a look in attached image here:
![Image of Yaktocat](https://lh6.googleusercontent.com/ROI_1WqLMp2cveNRaE4H2Tz_UJoCOWT0fbxFZX1SZvDc0o0f8m_aCdDktV6jRmb9d4LqVGnugf7yZGk=w1576-h655-rw)
1. Image with resolution 1829x3252 resized to exactly it resolution but file size change from 261 = 56.
2. Image with resolution 1125x2000 resized to smaller than it resolution but file size larger than original image.

Do you know why?

**Comment by danschumann** [comment]
I can't see the image you sent.  Do you have a different link?

**Comment by nghiapd92** [comment]
Please see here:
http://kyllynk.com/imgsize.png

**Comment by danschumann** [comment]
Still a broken link..?

**Comment by danschumann** [comment]
Closing til we can get a test case.
